// <auto-generated />
namespace yInvoice.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Add_EMails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_EMails));
        
        string IMigrationMetadata.Id
        {
            get { return "201409070905533_Add_EMails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
